export enum Category {
  Official = 1,
  Wikia = 2,
  Wikipedia = 3,
  Facebook = 4,
  Twitter = 5,
  Twitch = 6,
  Instagram = 8,
  YouTube = 9,
  iPhone = 10,
  iPad = 11,
  Android = 12,
  Steam = 13,
  Reddit = 14,
  Itch = 15,
  EpicGames = 16,
  Gog = 17,
  Discord = 18,
}
